---
# tasks file for sap_hana_sr_takeover
#
- name: Verify the role variables
  ansible.builtin.import_tasks:
    file: assert_vars.yml

- name: Get HDB online state
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "online:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  changed_when: false
  register: register_sap_hana_sr_takeover_online

# returns: 'none' or 'primary' on the primary system, 
#          the HSR replication method on the secondary system
- name: Get the mode of the HDB system
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "mode:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  changed_when: false
  register: register_sap_hana_sr_takeover_mode

##
# enable the right primary
#
- name: Fail, when the planned primary system cannot take over (no HSR configured)
  ansible.builtin.fail:
    msg: "This system is not part of a SAP HANA system replication setup."
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - register_sap_hana_sr_takeover_mode.stdout == "none"

- name: Make 'sap_hana_sr_takeover_primary' {{ sap_hana_sr_takeover_primary }} the new primary
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
    -sr_takeover
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - register_sap_hana_sr_takeover_mode.stdout != "primary"
    - not sap_hana_sr_takeover_handshake  

- name: Make 'sap_hana_sr_takeover_primary' {{ sap_hana_sr_takeover_primary }} the new primary - and suspend the old primary
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
    -sr_takeover --suspendPrimary
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  when:
    - ansible_hostname == sap_hana_sr_takeover_primary
    - register_sap_hana_sr_takeover_mode.stdout != "primary"
    - sap_hana_sr_takeover_handshake  

###
# register the secondary
#
- name: Register 'sap_hana_sr_takeover_secondary' {{ sap_hana_sr_takeover_secondary }} to the new primary system
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  when:
    - ansible_hostname == sap_hana_sr_takeover_secondary
    - register_sap_hana_sr_takeover_mode.stdout != sap_hana_sr_takeover_rep_mode
  block:
    - name: Ensure HDB on 'sap_hana_sr_takeover_secondary' is stopped
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
        /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/HDB stop
      args:
        executable: /bin/bash
      when:
        - register_sap_hana_sr_takeover_online.stdout == 'true'

    - name: Register 'sap_hana_sr_takeover_secondary' to the primary system
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
        /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
        -sr_register \
        --name="{{ sap_hana_sr_takeover_sitename }}" \
        --remoteHost={{ sap_hana_sr_takeover_primary }} \
        --remoteInstance={{ sap_hana_instance_number }} \
        --replicationMode={{ sap_hana_sr_takeover_rep_mode }} \
        --operationMode={{ sap_hana_sr_takeover_hsr_oper_mode }}
      args:
        executable: /bin/bash

## Check Online state and start HDB
- name: Get HDB online state
  ansible.builtin.shell: |
    set -o pipefail
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbnsutil \
    -sr_state | awk '($1 == "online:") {print $2}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  changed_when: false
  register: register_sap_hana_sr_takeover_online

- name: Ensure HDB is running
  ansible.builtin.shell: |
    source /usr/sap/{{ sap_hana_sid | upper }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/HDB start
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  when:
    - register_sap_hana_sr_takeover_online.stdout == 'false'
